# Fix the code so that assertion does not throw any error

# Your code here

user = User('John', 'Doe', 23)
assert user.get_name() == 'John Doe'
assert user.get_age() == 'I am 23 years old'
